version: '3'
services:
  app:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.staging
    ports:
      - "3000:3000"
    env_file:
      - ./.env.staging
  nginx:
    container_name: merchflow_frontend_nginx
    build: ./nginx
    ports:
      - "80:80"
  